version: "2"

silent: true

vars:
  EXE: kubico{{exeExt}}
  NODE_TAG_VERSION: 13.12.0-buster

tasks:
  run:
    desc: Build and run the web app
    cmds:
      - go run .

  build:
    desc: Build the web app
    cmds:
      - go generate
      - go build -v -o {{.EXE}}
      - packr2 clean

  cleanup:
    desc: Cleanup
    cmds:
      - go clean -n github.com/Ilyes512/kubico
      - if [ -x "$(command -v packr2)" ]; then packr2 clean; fi

  dl-deps:
    desc: Install tools required to build this app
    cmds:
      - task: go-get
        vars: { REPO: github.com/gobuffalo/packr/v2/packr2 }

  go-get:
    cmds:
      - go get -u {{.REPO}}

########################################################################################################################
#
# Docker
#
########################################################################################################################

  d:build:
    desc: Build docker container
    cmds:
      - docker build --tag ilyes512/kubico-builder:fromsource-builder --file ./build/builder/Dockerfile .
      - docker build --tag ilyes512/kubico:fromsource-scratch --file ./build/scratch/Dockerfile --build-arg KUBICO_VERSION=fromsource .

  d:run:
    desc: Run the container
    deps: [d:build]
    cmds:
      - |-
        if [ -s .env ]; then
          docker run --tty --interactive --rm --publish 8080:8080 --volume $(pwd)/.env:/.env ilyes512/kubico:fromsource;
        else
          docker run --tty --interactive --rm --publish 8080:8080 ilyes512/kubico:fromsource;
        fi

########################################################################################################################
#
# NODE / NPM
#
########################################################################################################################
  n:install:
    desc: Run "npm install"
    cmds:
      - docker run --rm --tty --user $(id -u):$(id -g) -v $(pwd)/assets:/assets --workdir /assets node:{{.NODE_TAG_VERSION}} npm install

  n:update:
    desc: Run "npm update"
    cmds:
      - docker run --rm --tty --user $(id -u):$(id -g) -v $(pwd)/assets:/assets --workdir /assets node:{{.NODE_TAG_VERSION}} npm update

  n:dev:
    desc: Run "npm run development"
    cmds:
      - docker run --rm --tty --user $(id -u):$(id -g) -v $(pwd)/assets:/assets --workdir /assets node:{{.NODE_TAG_VERSION}} npm run development

  n:prd:
    desc: Run "npm run development"
    cmds:
      - docker run --rm --tty --user $(id -u):$(id -g) -v $(pwd)/assets:/assets --workdir /assets node:{{.NODE_TAG_VERSION}} npm run production

  n:dev:watch:
    desc: Run "npm run development"
    cmds:
      - NODE_ENV=development postcss src/tailwind.css -o dist/tailwind.css -- --watch
