name: Docker build latest

on:
  push:
    branches: [master]
    paths-ignore:
      - README.md
      - .editorconfig
      - Taskfile.yml
jobs:
  build-latest:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to docker registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build containers
        run: |
          docker build --tag ilyes512/kubico-builder:latest --file ./build/builder/Dockerfile --build-arg COMPRESS=true .
          docker build --tag ilyes512/kubico:latest-scratch --file ./build/scratch/Dockerfile .
          docker build --tag ilyes512/kubico:latest-alpine --file ./build/alpine/Dockerfile .
      - name: Push containers
        run: |
          docker push ilyes512/kubico-builder:latest
          docker push ilyes512/kubico:latest-scratch
          docker push ilyes512/kubico:latest-alpine
